CREATE TABLE IF NOT EXISTS `#__productupdater_products` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `element` VARCHAR(255) NOT NULL DEFAULT '',
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `platform` VARCHAR(32) NOT NULL DEFAULT 'joomla',
  `type` VARCHAR(32) NOT NULL DEFAULT 'component',
  `description` TEXT NOT NULL,
  `maintainer` VARCHAR(255) NOT NULL DEFAULT '',
  `maintainer_url` VARCHAR(255) NOT NULL DEFAULT '',
	`catid` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `download_category` VARCHAR(255) NOT NULL DEFAULT '',
  `preview_image` VARCHAR(1024) NOT NULL DEFAULT '',
  `download_size` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `download_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `versions` LONGTEXT NOT NULL,
  `state` TINYINT(4) NOT NULL DEFAULT 0,
  `ordering` INT(11) NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `created_by` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `modified_by` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` INT(11) UNSIGNED,
  `checked_out_time` DATETIME,
  PRIMARY KEY (`id`),
  KEY `idx_element` (`element`),
	KEY `idx_catid` (`catid`),
  KEY `idx_state` (`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `#__productupdater_changelogs` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `entries` LONGTEXT NOT NULL,
  `state` TINYINT(4) NOT NULL DEFAULT 0,
  `ordering` INT(11) NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `created_by` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `modified_by` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` INT(11) UNSIGNED,
  `checked_out_time` DATETIME,
  PRIMARY KEY (`id`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_state` (`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
